### ISSUE TITLE
【道具】关于恋恋的头盔

### ISSUE THREAD

**Issue by Hakurei-Reimu-SkylarkStudio** [Hakurei-Reimu-SkylarkStudio/SEU-THC#1]
**@鵺鵺**
*    【道具】卡中恋恋的头盔应当为钢盔形而非软质。
        By:鵺鵺@Voicehe

**Comment by Voicehe** [comment]
是这个样子，，，大家有什么意见都可以说粗来，在我发的那个问题下也可以。
